"""add_compound_indexes

Revision ID: 30ac6dfbde63
Revises: 743db10cc8e7
Create Date: 2026-02-06 22:05:19.626056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ac6dfbde63'
down_revision: Union[str, None] = '743db10cc8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_performance_metrics_date', table_name='performance_metrics')
    op.create_index('ix_performance_metrics_model_id_date', 'performance_metrics', ['model_id', 'date'], unique=False)
    op.drop_index('ix_portfolio_snapshots_date', table_name='portfolio_snapshots')
    op.create_index('ix_portfolio_snapshots_model_id_date', 'portfolio_snapshots', ['model_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_snapshots_model_id_date', table_name='portfolio_snapshots')
    op.create_index('ix_portfolio_snapshots_date', 'portfolio_snapshots', ['date'], unique=False)
    op.drop_index('ix_performance_metrics_model_id_date', table_name='performance_metrics')
    op.create_index('ix_performance_metrics_date', 'performance_metrics', ['date'], unique=False)
    # ### end Alembic commands ###
