"""add_backtest_data_table

Revision ID: d8c4f8911cbb
Revises: 8eee6a1fcfbc
Create Date: 2026-01-18 19:52:42.280122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c4f8911cbb'
down_revision: Union[str, None] = '8eee6a1fcfbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('buy_hold_value', sa.Float(), nullable=False),
    sa.Column('traded_value', sa.Float(), nullable=False),
    sa.Column('new_highs', sa.Integer(), nullable=False),
    sa.Column('new_lows', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['trading_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Daily backtest portfolio values for visualization'
    )
    op.create_index(op.f('ix_backtest_data_date'), 'backtest_data', ['date'], unique=False)
    op.create_index(op.f('ix_backtest_data_model_id'), 'backtest_data', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_data_model_id'), table_name='backtest_data')
    op.drop_index(op.f('ix_backtest_data_date'), table_name='backtest_data')
    op.drop_table('backtest_data')
    # ### end Alembic commands ###
